// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDatabase() {
  return window['go']['main']['App']['CloseDatabase']();
}

export function DeleteRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRow'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetTableData(arg1) {
  return window['go']['main']['App']['GetTableData'](arg1);
}

export function GetTableSchema(arg1) {
  return window['go']['main']['App']['GetTableSchema'](arg1);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InsertRow(arg1, arg2) {
  return window['go']['main']['App']['InsertRow'](arg1, arg2);
}

export function OpenDatabase() {
  return window['go']['main']['App']['OpenDatabase']();
}

export function ReloadWindow() {
  return window['go']['main']['App']['ReloadWindow']();
}

export function UpdateRow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateRow'](arg1, arg2, arg3, arg4, arg5);
}
