// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseDatabase():Promise<void>;

export function DeleteRow(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteQuery(arg1:string):Promise<main.QueryResult>;

export function GetDatabasePath():Promise<string>;

export function GetTableData(arg1:string):Promise<main.QueryResult>;

export function GetTableSchema(arg1:string):Promise<Array<main.Column>>;

export function GetTables():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InsertRow(arg1:string,arg2:Array<string>):Promise<void>;

export function OpenDatabase():Promise<string>;

export function ReloadWindow():Promise<void>;

export function UpdateRow(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
